module.exports = {
	'import/default': 'error',
	'import/export': 'error',
	'import/extensions': 'error',
	'import/first': 'error',
	'import/imports-first': 'error',
	'import/max-dependencies': 'error',
	'import/named': 'error',
	'import/namespace': 'error',
	'import/newline-after-import': 'off',
	'import/no-absolute-path': 'error',
	'import/no-amd': 'error',
	'import/no-commonjs': 'off',
	'import/no-deprecated': 'error',
	'import/no-duplicates': 'error',
	'import/no-dynamic-require': 'error',
	'import/no-extraneous-dependencies': 'error',
	'import/no-internal-modules': 'off',
	'import/no-mutable-exports': 'error',
	'import/no-named-as-default': 'error',
	'import/no-named-as-default-member': 'error',
	'import/no-namespace': 'error',
	'import/no-nodejs-modules': 'off',
	'import/no-restricted-paths': 'off',
	'import/no-unassigned-import': 'error',
	'import/no-unresolved': ['error', {commonjs: true}],
	'import/no-webpack-loader-syntax': 'error',
	'import/order': 'error',
	'import/prefer-default-export': 'error',
	'import/unambiguous': 'off',
};
