module.exports = {
  'import/default': 'error',
  'import/export': 'error',
  'import/extensions': 'error',
  'import/imports-first': 'error',
  'import/named': 'error',
  'import/namespace': 'error',
  'import/newline-after-import': 'off',
  'import/no-amd': 'error',
  'import/no-commonjs': 'off',
  'import/no-deprecated': 'error',
  'import/no-duplicates': 'error',
  'import/no-extraneous-dependencies': 'error',
  'import/no-mutable-exports': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-namespace': 'error',
  'import/no-nodejs-modules': 'off',
  'import/no-unresolved': 'error',
  'import/order': 'error',
  'import/prefer-default-export': 'error',
};
