const tabWidth = 2;

module.exports = {
  'react/display-name': 'error',
  'react/forbid-prop-types': ['error', {forbid: ['any']}],
  'react/jsx-boolean-value': 'error',
  'react/jsx-closing-bracket-location': ['error', 'after-props'],
  'react/jsx-curly-spacing': 'error',
  'react/jsx-equals-spacing': 'error',
  'react/jsx-first-prop-new-line': 'error',
  'react/jsx-handler-names': 'error',
  'react/jsx-indent': ['error', tabWidth],
  'react/jsx-indent-props': 'off',
  'react/jsx-filename-extension': ['error', {extensions: ['.js']}],
  'react/jsx-key': 'error',
  'react/jsx-max-props-per-line': 'off',
  'react/jsx-no-bind': 'error',
  'react/jsx-no-duplicate-props': 'error',
  'react/jsx-no-literals': 'error',
  'react/jsx-no-target-blank': 'error',
  'react/jsx-no-undef': 'error',
  'react/jsx-pascal-case': 'error',
  'react/jsx-sort-props': 'error',
  'react/jsx-sort-prop-types': 'off', // Deprecated. Left in for unused warning.
  'react/jsx-space-before-closing': 'off',
  'react/jsx-uses-react': 'error',
  'react/jsx-uses-vars': 'error',
  'react/no-comment-textnodes': 'error',
  'react/no-danger': 'error',
  'react/no-deprecated': 'error',
  'react/no-did-mount-set-state': 'off',
  'react/no-did-update-set-state': 'error',
  'react/no-direct-mutation-state': 'error',
  'react/no-is-mounted': 'error',
  'react/no-multi-comp': 'off',
  'react/no-render-return-value': 'error',
  'react/no-set-state': 'off',
  'react/no-string-refs': 'error',
  'react/no-unknown-property': 'error',
  'react/prefer-es6-class': 'error',
  'react/prefer-stateless-function': 'error',
  'react/prop-types': 'error',
  'react/react-in-jsx-scope': 'error',
  'react/require-extension': 'error',
  'react/require-optimization': 'off', // Doesn't ignore stateless components.
  'react/require-render-return': 'error',
  'react/self-closing-comp': 'error',
  'react/sort-comp': 'error',
  'react/sort-prop-types': 'error',
  'react/wrap-multilines': ['error', {
    declaration: false,
    assignment: false,
    return: true,
  }],
};
